version: 2
updates:

  - package-ecosystem: "maven"
    directory: "backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "zone.js"
          - "typescript"
          - "tailwindcss"
      karma:
        patterns:
          - "karma"
          - "karma-*"
  
  - package-ecosystem: "npm"
    directory: "backend/auth-frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "zone.js"
          - "typescript"
          - "tailwindcss"
      karma:
        patterns:
          - "karma"
          - "karma-*"
