version: 2
updates:

  - package-ecosystem: "mvn"
    directory: "/backend/"
    schedule:
      interval: "daily"
    # Add assignees
    assignees:
      - "octocat"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "daily"
    # Add assignees
    assignees:
      - "octocat"
    open-pull-requests-limit: 5
