version: 2
updates:

  - package-ecosystem: "maven"
    directory: "backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  
  - package-ecosystem: "npm"
    directory: "backend/auth-frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
