version: '3.7'

services:

  # Authorization service
  auth-service:
    ports:
      - "5005:5005"
    command: ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments=\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005\"", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=dev"]