version: '3.7'

services:

  # Frontend
  frontend:
    build:
      context: frontend
      dockerfile: dev.dockerfile
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - type: bind
        source: ./frontend
        target: /opt/frontend
    environment:
      TZ: America/Santiago

  # Authorization service
  auth-service:
    build:
      context: backend
      dockerfile: dev.dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./backend/src/
        target: /opt/backend/src/
      - type: bind
        source: ~/.m2/repository/
        target: /root/.m2/repository/
    networks:
      backend:
        aliases:
          - auth-service
    environment:
      TZ: America/Santiago
      spring.profiles.active: dev
      spring.cloud.consul.host: consul
      spring.cloud.consul.port: 8500
      spring.data.mongodb.host: mongodb
      spring.data.mongodb.port: 27017
  
  # MongoDB
  mongodb:
    image: mongo:5.0.3
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/:/data/db
    networks:
      backend:
        aliases:
          - mongodb
    environment:
      TZ: America/Santiago

networks:
  backend:
    name: backend