version: '3.7'

services:

  # Authorization service
  auth-service:
    ports:
      - "5005:5005"
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"
    command: ["./mvnw", "spring-boot:run", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=dev"]