version: '3.7'

services:

  # Frontend
  frontend:
    build:
      context: frontend
      dockerfile: dev.dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "./frontend:/opt/frontend"
    environment:
      TZ: America/Santiago

  # Authorization service
  auth-service:
    build:
      context: backend
      dockerfile: dev.dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "./backend/src/:/opt/backend/src/"
      - "./backend/target/:/opt/backend/target/"
      - "~/.m2/repository/:/root/.m2/repository/"
    networks:
      backend:
        aliases:
          - auth-service
    environment:
      TZ: America/Santiago
      spring.profiles.active: dev
      spring.cloud.consul.host: consul
      spring.cloud.consul.port: 8500
      spring.data.mongodb.host: mongodb
      spring.data.mongodb.port: 27017
      LOG_LEVEL: INFO
      LOGGING_LEVEL_ROOT: INFO
      OIDC_MANAGEMENT_URL: "http://localhost:8080"
      OIDC_MANAGEMENT_DEFAULT_SERVICEACCOUNT_ENABLED: "true"
      OIDC_MANAGEMENT_DEFAULT_SERVICEACCOUNT_CLIENTID: "eb5d9c2a-b5aa-4467-b4b4-79ae82eee0d8"
      OIDC_MANAGEMENT_DEFAULT_SERVICEACCOUNT_CLIENTSECRET: "05009f8d-97d7-4601-8852-b196ba7fdf41"
      OIDC_MANAGEMENT_DEFAULT_SERVICEACCOUNT_REDIRECTURIS_0_: "http://127.0.0.1/oauth/callback"
      OIDC_MANAGEMENT_DEFAULT_AUTHORITY_ENABLED: "true"
      OIDC_MANAGEMENT_DEFAULT_USERACCOUNT_ENABLED: "true"
      OIDC_MANAGEMENT_DEFAULT_USERACCOUNT_USERNAME: "admin"
      OIDC_MANAGEMENT_DEFAULT_USERACCOUNT_PASSWORD: "admin"
      OIDC_MANAGEMENT_DEFAULT_SCOPE_ENABLED: "true"
  
  # MongoDB
  mongodb:
    image: mongo:5.0.3
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/:/data/db
    networks:
      backend:
        aliases:
          - mongodb
    environment:
      TZ: America/Santiago

networks:
  backend:
    name: backend