spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oidc.management.url}/oauth2/jwks

oidc:
  management:
    jwk:
      strategy: simple
      provider: simple
      schedule: 0 * * ? * *
      cache:
        value: ""
        cacheManager: "concurrentMapJwkCacheManager"
        condition: ""
      vault:
        path: "jwks"