spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oidc.management.url}/oauth2/jwks

oidc:
  management:
    jwk:
      strategy: simple
      provider: simple
      scheduled:
        cron: "0 * * ? * *"
      renewing:
        cron: "0 0 0/2 ? * *"
        limit: 12
      cache:
        value: ""
        cacheManager: "concurrentMapJwkCacheManager"
        condition: ""
      vault:
        path: "jwks"